server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:drone_h2;
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: validate
    show-sql: false
    database: h2
    properties:
        dialect: org.hibernate.dialect.H2
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    repeatable-sql-migration-prefix: R