insert into drones (id, serial_number, model, weight_limit, battery_capacity, drone_state)
values (nextval('drone_id_generator'), 'DRONE001', 'LIGHTWEIGHT', 200, 100, 'IDLE'),
       (nextval('drone_id_generator'), 'DRONE002', 'MIDDLEWEIGHT', 300, 100, 'IDLE'),
       (nextval('drone_id_generator'), 'DRONE003', 'CRUISERWEIGHT', 400, 100, 'IDLE'),
       (nextval('drone_id_generator'), 'DRONE004', 'HEAVYWEIGHT', 500, 100, 'IDLE'),
       (nextval('drone_id_generator'), 'DRONE005', 'LIGHTWEIGHT', 200, 100, 'IDLE'),
       (nextval('drone_id_generator'), 'DRONE006', 'MIDDLEWEIGHT', 300, 100, 'IDLE'),
       (nextval('drone_id_generator'), 'DRONE007', 'CRUISERWEIGHT', 400, 100, 'IDLE'),
       (nextval('drone_id_generator'), 'DRONE008', 'HEAVYWEIGHT', 500, 100, 'IDLE'),
       (nextval('drone_id_generator'), 'DRONE009', 'LIGHTWEIGHT', 200, 100, 'IDLE'),
       (nextval('drone_id_generator'), 'DRONE010', 'MIDDLEWEIGHT', 300, 100, 'IDLE');
insert into medications (id, medication_name, weight, code, image_url, drone_id)
values (nextval('medication_id_generator'), 'Medication 1', 100, 'CODE1', './images/medication1.jpg', (select id from drones where serial_number = 'DRONE001')),
       (nextval('medication_id_generator'), 'Medication 2', 50, 'CODE2', './images/medication2.jpg', (select id from drones where serial_number = 'DRONE001')),
       (nextval('medication_id_generator'), 'Medication 3', 75, 'CODE3', './images/medication3.jpg', (select id from drones where serial_number = 'DRONE002')),
       (nextval('medication_id_generator'), 'Medication 4', 200, 'CODE4', './images/medication4.jpg', (select id from drones where serial_number = 'DRONE002')),
       (nextval('medication_id_generator'), 'Medication 5', 150, 'CODE5', './images/medication5.jpg', (select id from drones where serial_number = 'DRONE003')),
       (nextval('medication_id_generator'), 'Medication 6', 125, 'CODE6', './images/medication6.jpg', (select id from drones where serial_number = 'DRONE003')),
       (nextval('medication_id_generator'), 'Medication 7', 80, 'CODE7', './images/medication7.jpg', (select id from drones where serial_number = 'DRONE004')),
       (nextval('medication_id_generator'), 'Medication 8', 40, 'CODE8', './images/medication8.jpg', (select id from drones where serial_number = 'DRONE005')),
       (nextval('medication_id_generator'), 'Medication 9', 100, 'CODE9', './images/medication9.jpg', (select id from drones where serial_number = 'DRONE005')),
       (nextval('medication_id_generator'), 'Medication 10', 50, 'CODE10', './images/medication10.jpg', (select id from drones where serial_number = 'DRONE005')),
       (nextval('medication_id_generator'), 'Medication 11', 75, 'CODE11', './images/medication11.jpg', (select id from drones where serial_number = 'DRONE006')),
       (nextval('medication_id_generator'), 'Medication 12', 200, 'CODE12', './images/medication12.jpg', (select id from drones where serial_number = 'DRONE006')),
       (nextval('medication_id_generator'), 'Medication 13', 150, 'CODE13', './images/medication13.jpg', (select id from drones where serial_number = 'DRONE007')),
       (nextval('medication_id_generator'), 'Medication 14', 125, 'CODE14', './images/medication14.jpg', (select id from drones where serial_number = 'DRONE007')),
       (nextval('medication_id_generator'), 'Medication 15', 80, 'CODE15', './images/medication15.jpg', (select id from drones where serial_number = 'DRONE008')),
       (nextval('medication_id_generator'), 'Medication 16', 40, 'CODE16', './images/medication16.jpg', (select id from drones where serial_number = 'DRONE008')),
       (nextval('medication_id_generator'), 'Medication 17', 100, 'CODE17', './images/medication17.jpg', (select id from drones where serial_number = 'DRONE009')),
       (nextval('medication_id_generator'), 'Medication 18', 50, 'CODE18', './images/medication18.jpg', (select id from drones where serial_number = 'DRONE009')),
       (nextval('medication_id_generator'), 'Medication 19', 75, 'CODE19', './images/medication19.jpg', (select id from drones where serial_number = 'DRONE010')),
       (nextval('medication_id_generator'), 'Medication 20', 200, 'CODE20', './images/medication20.jpg', (select id from drones where serial_number = 'DRONE010'));
